### ISSUE TITLE
Incresing photon packets does not work when using the fiber source

### ISSUE THREAD

**Issue by weoan** [xopto/pyxopto#1]
When I use a fiber  source in the simulator, it can not get more accurate results with  Incresing the photon packets.The same problem also occurr in the example examples/mcml/reflectance_optical_probes.py.
 I'm not sure whether there are some bugs I don't know and any help would be appreciated.

**Comment by xopto** [comment]
Please provide a minimum example that illustrates the issue. One reason that might lead to failed simulations with a large number of photon packets is the Timeout Detection & Recovery OS feature (Windows OS) which resets the GPU if computations are taking longer than about 2 s. This applies if you are using the same GPU for OS and computations. You can increase the timeout interval or entirely disable TDR for NVIDIA cards by following these instructions:
https://docs.nvidia.com/gameworks/content/developertools/desktop/timeout_detection_recovery.htm

**Comment by xopto** [comment]
For a six-around-one probe the reflectance noise drops with the number of launched photon packets as expected. The following figure illustrates this by progressively increasing the number of launched photon packets and observing the spread of reflectance collected through the 6 fibers that surround the central source fiber.  
![six-around-one-packets](https://user-images.githubusercontent.com/86132678/163651166-486a77b4-6749-4357-8395-f22cc9adc746.png)
The above figure was generated with the following file: 
[six-around-one-packets.zip](https://github.com/xopto/pyxopto/files/8498874/six-around-one-packets.zip)

Note that the simulation radius of 10 mm used in the example needs to be adapted if a larger source-detector separation is used or a wider range of optical properties is applied to the sample. The attached example was run with an additional common set of OpenCL build options that tend to speed up the simulations by about 30% (additional parameter `cl_build_options=[mc.cloptions.FastMath]` of `mc.Mc`).

**Comment by weoan** [comment]
The problem seems to occur when I choose  cpu as the computational device. The following figures illustrate this issue by using different computing device when progressively increasing the number of launched photon packets .
![image](https://user-images.githubusercontent.com/86721785/163726472-1220bdf6-1ebd-4352-8382-e26a3a3e35a4.png)
![image](https://user-images.githubusercontent.com/86721785/163726659-b942c730-d55b-4ca0-baec-d4f76a4f610b.png)
The above figure was generated with the following file:
[Test_Different_Devices.zip](https://github.com/xopto/pyxopto/files/8502184/Test_Different_Devices.zip)

**Comment by xopto** [comment]
Thank you for the example. I see the same issue with a CPU device. The issue seems to be related to the OpenCL work group size. If the work group size is manually set to a value that is smaller than the number of CPU cores, then the results are as expected (from 1 to 4 on Intel i7-4790 CPU). The work group size can be set through the `wgsize` parameter of the `Mc.run` method:
`detector_radial4 = mc_obj_radial.run(nphotons, wgsize=4, verbose=True)[-1]`
Until we have a better understanding of the issue and hopefully an effective solution I suggest that you manually specify the work group size for CPU devices by using the `wgsize` parameter of the `Mc.run` method.
