### ISSUE TITLE
How to build voxel meshes with different element sizes along Z directions

### ISSUE THREAD

**Issue by RickyKaku** [xopto/pyxopto#11]
I am planning to build a voxel model but the skin-layer thicknesses vary in orders of magnitudes. I want to make the mesh element dense at thin layers and sparse at thick layers. Any good recommendations to achieve this? Your help would be greatly appreciated.

**Comment by xopto** [comment]
The voxel size will be the same for the entire volume but you can make the size different along the x, y, and z directions. Note that the voxel size used to describe the medium can differ from the voxel size used by the fluence/deposition detectors.
