### ISSUE TITLE
Issue regarding Opencl and Overflow

### ISSUE THREAD

**Issue by Mrinmoyst1** [xopto/pyxopto#15]
Hello, recently I modeled a 7 layer human skin Monte Carlo simulation. But, after running this first time, it ran perfectly with photons 10e4. But after some time, I am facing several issues. Sometimes, this "---------------------------------------------------------------------------
LogicError                                Traceback (most recent call last)
Cell In[19], line 39
     35 mc_obj.layers[7].mus = mus7(w)
     38 # detector = mc_obj.run(nphotons, verbose=True)[-1]
---> 39 trace, fluence_res, detector = mc_obj.run(100e3)
     40 reflectance_spectrum[i] = detector.top.reflectance[0] * np.pi * sp_r**2
     42 wav[i] = w

File [c:\Users\user\anaconda3\envs\mcs2\Lib\site-packages\pyxopto-0.2.2-py3.11.egg\xopto\mcml\mc.py:953](file:///C:/Users/user/anaconda3/envs/mcs2/Lib/site-packages/pyxopto-0.2.2-py3.11.egg/xopto/mcml/mc.py:953), in Mc.run(self, nphotons, out, wgsize, maxthreads, copyseeds, exportsrc, verbose)
    919 t1 = time.perf_counter()
    921 # call the kernel
    922 self._cl_exec.McKernel(
    923     cl_queue, globalWG, localWG,
    924 
    925     np.dtype(self._types.np_cnt).type(nphotons),
    926     cl_buffers['num_processed_packets'],
    927 
    928     cl_buffers['num_kernels'],
    929 
    930     np.dtype(self._types.np_float).type(self._rmax),
    931 
    932     cl_buffers['rng_seeds_x'],
    933     cl_buffers['rng_seeds_a'],
    934 
    935     np.uint32(len(self._layers)),
    936     cl_buffers['layers'],
    937 
    938     cl_buffers['source'],
    939 
    940     cl_buffers['surface_layouts'],
    941 
    942     cl_buffers['trace'],
    943 
    944     cl_buffers['fluence'],
    945 
    946     cl_buffers['detectors'],
    947 
    948     self.cl_r_float_lut(False),
    949 
    950     self.cl_rw_int_buffer(),
    951     self.cl_rw_float_buffer(),
    952     self.cl_rw_accumulator_buffer(),
--> 953 ).wait()
    955 t2 = time.perf_counter()
    957 # get the number of concurrent kernels that were used to process the job

LogicError: clWaitForEvents failed:" also sometimes this "OverflowError: Python int too large to convert to C long". I think it's handling floating point values and that's why it's happening. After I reduced the photon packets to 10e3, the code is running successfully. But when I increase the number of photon packets, these type of issues are occurring. 

I think the solution is here: https://xopto.github.io/pyxopto/docs/html/source/mcml/simulator_data_types.html
But, unfortunately I am not getting it. Could you please give me an example about it's implementation? Thanks!

**Comment by xopto** [comment]
Please include a minimal working example of python code that reproduces the observed errors.
