### ISSUE TITLE
Problems using pyopencl

### ISSUE THREAD

**Issue by micaloping** [xopto/pyxopto#27]
Hi everyone.
It's my first time with pyxopto and opencl, and for several days I have been having a problem using them, I have only tried the basic.py example. I have tried everything, installing the libraries, installing Intel® oneAPI Base Toolkit, installing the drivers from Intel web, etc and nothing changes.

I've also tried on Manjaro Linux, installing all the necessary libraries from AUR, but the same thing keeps happening to me.

My card is Intel Iris Xe and the error for example in windows is the following:

![{70135378-B774-4FDD-9E09-3ACF96F55E44}](https://github.com/user-attachments/assets/ae847d52-3178-4428-8967-3cac6cc04a0f)

```
_`  File "C:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyxopto-0.2.3-py3.12.egg\xopto\mcbase\mcworker.py", line 198, in __init__
    self._cl_queue = cl.CommandQueue(
                     ^^^^^^^^^^^^^^^^
TypeError: __init__(): incompatible function arguments. The following argument types are supported:
    1. __init__(self, context: pyopencl._cl.Context, device: pyopencl._cl.Device | None = None, properties: object = 0) -> None

Invoked with types: pyopencl._cl.CommandQueue, pyopencl._cl.Context, kwargs = { properties: NoneType }`_

```
If anyone have some idea of what I can do, is welcome :)
Thanks a lot for your help!

**Comment by micaloping** [comment]
I found the solution in Issue https://github.com/xopto/pyxopto/issues/24  And now it works!
Thanks!

**Comment by Randall531** [comment]
Hi, I have tried the same solution from your link by changing to cl_cq_properties = 0. However, i still get the same error,

TypeError: __init__(): incompatible function arguments. The following argument types are supported:
    1. __init__(self, context: pyopencl._cl.Context, device: pyopencl._cl.Device | None = None, properties: object = 0) -> None

Invoked with types: pyopencl._cl.CommandQueue, pyopencl._cl.Context, kwargs = { properties: NoneType }`_

Did you do any additional steps?
