### ISSUE TITLE
Setting reflectance of the sample volume walls?

### ISSUE THREAD

**Issue by patrickcgray** [xopto/pyxopto#32]
I've been trying to find this in the documentation, but is there a way to set a reflectance value for the walls of the sample volume? I'd like to understand the light reaching detectors in certain geometry with and without reflection off the wall of the volume.

Thanks!

**Comment by xopto** [comment]
The top and bottom surfaces of the sample volume can be customized through the exposed API. See LambertianReflector for a basic example. Unfortunately, the side walls would require changes to the OpenCL kernel function mcsim_boundary, which handles all the interactions at the layer/voxel boundaries.

**Comment by patrickcgray** [comment]
Okay, I see this now, thank you!
