### ISSUE TITLE
3D mesh import capabilities for generating voxelized geometry

### ISSUE THREAD

**Issue by ImanKafian** [xopto/pyxopto#4]
Hi,

I would like to ask you whether there is a possibility to import a 3d geometry or any point-cloud file for creating a voxelized mesh for optical simulation. Although in all the mcvox examples, the voxelized geometry was specified in the script, I believe it must be feasible to import a 3D file and specify it as the voxelized geometry. I just wanted to ask you for a clear example of how to import such 3D model and assign its material properties accordingly.

Thank you very much.

**Comment by ImanKafian** [comment]
Hi, 

Many thanks for your prompt response. I tried to run the script however, I received the following error:
pyopencl._cl.LogicError: Context failed: INVALID_PLATFORM

I tried to modify the code and introduce cl_device as a cpu device in the MC object with a wgsize of 6 in the run method. However, I am still receiving the same error. 

This is the full traceback:
stl_vox.py - line 65:
mc_obj = mc.Mc(voxels, materials, source, fluence=fluence, cl_devices=cl_device)
mcvox/mc.py - line 342 - in __init__
cl_profiling=cl_profiling, rnginit=rnginit)
mcbase/mcworker.py, line 1207, in __init__
super().__init__(*args, **kwargs)
mcbase/mcworker.py, line 195, in __init__
self._cl_context = cl.Context(self._cl_devices)
pyopencl._cl.LogicError: Context failed: INVALID_PLATFORM

I would appreciate it if you could please let me know what causes this error.

Thank you very much.

**Comment by xopto** [comment]
Hi,

The error comes from the OpenCL driver and with the provided information I can't give more specific help.

Try to list your OpenCL devices with:
  mc.clinfo.info()

Select a GPU or CPU device manually (use the optional platform and/or device parameters to select a specific OpenCL device):
  cl_device = mc.clinfo.gpu(platform='intel', device='hd')
  cl_device = mc.clinfo.cpu(platform='intel')
  cl_device = mc.clinfo.gpu(platform='nvidia')

Pass the device into the MC constructor as:
mc_obj = mc.MC(..., cl_devices=cl_device)

Note that if using a CPU device, the workgroup size should be set to less than the number of CPU cores (start with 1):
mc_obj = mc.MC(..., cl_devices=cl_device)
mc_obj.run(..., wgsize=1)

You may also try to run a basic OpenCL example from PyOpenCL documentation and see if that works:
https://documen.tician.de/pyopencl/

**Comment by ImanKafian** [comment]
Hi,

Many thanks for your help. It solved the problem.
