### ISSUE TITLE
How to add multiple light sources?

### ISSUE THREAD

**Issue by RickyKaku** [xopto/pyxopto#5]
Do you support multiple light sources for the Voxelized Monte Carlo simulations? 
I have tried source = {mc.mcsource.IsotropicPoint((-0.2e-3,0.0, 0.0)),mc.mcsource.IsotropicPoint((0.2e-3,0.0, 0.0))}
but it gives error when deploying deposit = mc_obj.run(nphotons, verbose=True)[1].
Any good suggestions to perform multiple light sources? Thank you!

**Comment by xopto** [comment]
Using multiple sources in a single Mc instance is not directly supported. However, there are at least two solutions for simulations with multiple sources.

1. Create one Mc instance for each source and run the simulations independently. Merge the simulation results. The merging/superposition will be trivial if the simulations across all the Mc instances (sources) are run with an equal number of photon packets.
2. Create a custom source class by modifying one of the available sources. This solution is more complex as it requires both Python and OpenCL code.

The first solution will be easier to implement for multiple isotropic point sources.

**Comment by RickyKaku** [comment]
Thank you very much for your response, so compared to solution 1 and 2, I am wondering if 3 would significantly reduce the simulation time?
