### ISSUE TITLE
How to set multiple detectors or visualize the internal voxel boundaries

### ISSUE THREAD

**Issue by RickyKaku** [xopto/pyxopto#7]
Currently the detectors are available at top and bottom but I don't see an example to specify the z axis location of the detectors. For an example, if I added an air layer above the skin, then the detector.top will give the reflectance in the air, if I still want to place it on the skin, what shall I do? Or is there a way to convert the fluence at the surface layer directly to the reflections? Thank you.

**Comment by xopto** [comment]
Reflectance/transmittance detectors are directly supported only on the outer surface of the sample volume. The first material in the list of materials will define the optical properties of the medium that surrounds the sample. For the case of a skin sample surrounded by air, configure the first material (index 0) as nonabsorbing (mua = 0) and non-scattering (mus = 0) with a refractive index 1.
For custom handling of photon packets at arbitrary (internal) voxel boundaries the kernel would have to be modified by introducing an additional detector callback immediately after a packet crosses a voxel boundary. Then you would have to implement a custom detector class that with the relevant OpenCL code. Briefly, the OpenCL detector code would first check if the crossed voxel boundary represents a detector and then write/accumulate the weight or any other quantity of interest to a global memory buffer/accumulator (like the existing surface or fluence detectors do). Note that such modification will very likely come with a heavy performance cost.

**Comment by RickyKaku** [comment]
Thank you very much for the help!

**Comment by RickyKaku** [comment]
It looks like the example of mcxyz.c https://omlc.org/software/mc/mcxyz/index.html not only gives the deposited energy but also the relative fluence rate (Figure 1.D), is it possible to obtain the figure with pyxopto?
